// Get all tables
GET http://localhost:4000/tables

###
// Book table 2
PUT http://localhost:4000/tables/491df4f6-4527-4a17-af0f-eb0b2aa55b81

content-type: application/json



###
// Add a new table
POST http://localhost:4000/tables
content-type: application/json

{"name":"Table 7","seats":"8","available":"true"}

###
// Delete a table "test"
DELETE http://localhost:4000/tables/1959bda4-1136-4c25-90f2-ca7dc1a7a1f9

###
// Testing coming functions
POST http://localhost:4000/reservation
content-type: application/json

{"date":"2021-12-04", "table":"2"}